# Usa una imagen base de Python
FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY requirements.txt ./

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto 
COPY pipeline.pkl .
COPY inference.py .
COPY clases.py .

# Comando para ejecutar la aplicación al iniciar el contenedor
CMD [ "python", "./inference.py" ]